### PR TITLE
Promises support in hooks

### LINKED ISSUE #19: Async hooks
I believe [hooks](https://github.com/SierraSoftworks/Iridium/blob/release/lib/Hooks.ts) should be able to return promises. Otherwise they become useless sometimes.

### PR DESCRIPTION
**Pull request by louy**
Closes #19

### CODE REVIEW

**Comment by louy** [comment]
@SPARTAN563 could you take a look?

**Comment by SPARTAN563** [comment]
Thanks @louy, I'll take a look through this and let's also discuss on #19 to see if this is in fact the best approach to take. I've added a bit of context there for the design motivations and maybe a possible solution which satisfies both your use case in a way which doesn't impact others.

**Comment by SPARTAN563** [comment]
Hi @louy, I've merged this into #22 with some optimizations, additional tests and docs - will need to benchmark the performance difference - but by the looks of it there's about a 9% hit on insert performance while read performance stays about the same. Would appreciate it if you could run the benchmark script on your side and take a look as well (the ratio to MongoDB's native driver is generally what you'll be interested in, as that should remain relatively consistent across platforms).

P.S. I'll make sure to merge this PR in before I merge #22 to ensure you get the commit credit :wink:

**Comment by louy** [comment]
Sorry about yesterday. Got busy with some [stuff](https://github.com/urbanmassage/opool) and couldn't reply.

I see what you did in #22. I had something else in mind though to avoid affecting the performance.

Why not check the return values of hooks after you call them. If it has property `.then` then it's a Thenable. Otherwise, just move on.

**Comment by louy** [comment]
Unless that's what `Promise.resolve` does. I'm not sure 😬

**Comment by SPARTAN563** [comment]
`Promise.resolve` does that and a bit more, technically it also checks whether it is a "trusted promise" (along the lines of `promise instanceof Bluebird`) and if not, will wrap it in a Bluebird promise. This ensures that calling methods like `.map()` on it will continue to function and keeps the system a bit less fragile.

**Comment by louy** [comment]
Makes sense. I'll check benchmarks and see if I can come up with any improvement.

**Comment by SPARTAN563** [comment]
Released in [6.3.0](https://github.com/SierraSoftworks/Iridium/releases/tag/v6.3.0) - if we manage to make any improvements, they'll likely go out in a patch release like `v6.3.1`.

**Pull request merged**
