### PR TITLE
Unit test that reveals bug in test.save()

### PR DESCRIPTION
**Pull request by fduplessisduplessis**
I picked up another bug in save() and would like to submit this unit test that breaks the build. I don't currently have time to fix it, as it looks quite complex. I will, however, make time if the fairies don't fix it overnight.

### CODE REVIEW

**Comment by SPARTAN563** [comment]
Thanks, I'll take a look at this and see what I can find

**Comment by SPARTAN563** [comment]
Okay, I've got a small reproduction case for this, it's an issue with the diff calculation when you both change the contents of an array of complex objects by modifying properties on those complex objects while reducing the length of the array itself.

```typescript
const original = { array: [
  { x: 1, y: 1 },
  { x: 2, y: 2 }
]}

const current = { array: [
  { x: 1, y: 2 }
]}

const expectedDiff = {
  "$set": {
    "array.0.y": 2
  },
  "$pull": {
    "array": { x: 2, y: 2 }
  }
}

const brokenDiff = {
  "$pull": {
    "array": { x: 2, y: 2 }
  }
}
```

**Comment by SPARTAN563** [comment]
I've managed to resolve this specific issue and updated the test suite to make it more clear what was breaking, it's building the release for v7.2.5 right now and I'll let you know as soon as that is out. Thanks for the comprehensive reproduction case, definitely made identifying the core issue a lot easier.

**Comment by SPARTAN563** [comment]
Version 7.2.5 has been released and should address this issue - let me know if anything else goes wonky.

**Comment by fduplessisduplessis** [comment]
Thank you!!

**Pull request merged**
